version: '2.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    environment:
      - ENVIRONMENT=LOCAL
      - LOG_LEVEL=INFO
