version: '2.1'

services:
  postgres-test:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=billing_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    environment:
      - ENVIRONMENT=TESTING
      - LOG_LEVEL=INFO
      - PG_HOST=postgres-test
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=secret
      - PG_DB_NAME=billing_test
    depends_on:
      postgres-test:
        condition: service_healthy
